// Generated by CoffeeScript 1.4.0
var get, set;

get = Em.get;

set = Em.set;

module.exports = Em.Mixin.create({
  sortedContent: (function() {
    var content;
    content = this.get('content') || [];
    return Em.ArrayController.create(Em.SortableMixin, {
      content: content.toArray(),
      sortProperties: this.get('sortProperties'),
      sortAscending: this.get('sortAscending')
    });
  }).property('content.isLoaded', 'content.@each', 'sortProperties', 'sortAscending')
});
